apiVersion: networking.kettle.io/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: kettle
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec:
  vlan: 100
  cidr: "10.10.0.0/24"
  gateway: "10.10.0.1"
  name: vlan100
  ipRange: "10.10.0.10-10.10.0.20"
  excludeIPs:
    - "10.10.0.11"
    - "10.10.0.12"

