apiVersion: networking.kettle.io/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: kettle
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec:
  cidr: "10.10.0.0/24"
  gateway: "10.10.0.1"
  name: network-sample
  ipRange: "10.10.0.10-10.10.0.20"

